Fix for compiler error with Clang on Mac
error: ordered comparison between pointer and zero
Simply needed to derefence the pointer for integer comparison with 0.